# to use orbs, must use version >= 2.1
version: 2.1
parameters:
  run-schedule:
      type: boolean
      default: false
orbs:
  # import Cypress orb by specifying an exact version
  cypress: cypress-io/cypress@1.29.0
workflows:
  build:
    when: <<pipeline.parameters.run-schedule>>
    jobs:
      # "cypress" is the name of the imported orb
      # "run" is the name of the job defined in Cypress orb
      - cypress/run:
          spec: cypress/integration/dreamhome_spec.js
          store_artifacts: true
          no-workspace: true