# to use orbs, must use version >= 2.1
version: 2.1
orbs:
  # import Cypress orb by specifying an exact version
  cypress: cypress-io/cypress@1.7.0
workflows:
  build:
    jobs:
      # "cypress" is the name of the imported orb
      # "run" is the name of the job defined in Cypress orb
      - cypress/run:
          spec: cypress/integration/smarthome_spec.js
          post-steps:
            - store_artifacts:
                path: /root/project/cypress/screenshots/smarthome_spec.js
                destination: screenshots
    triggers:
        - schedule:
            cron: "0 5 * * *"
            filters:
              branches:
                only:
                  - dream